version: '3.1'

services:

  moviedetailsapi:
    image: eassbhhtgu/moviedetailsapi:latest
    ports:
      - "35242:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
